name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:   # allows manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: apply   # <-- environment must be at job level

    permissions:
      id-token: write   # Required for OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::111225938018:role/github-odic-chamu
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file=terraform.tfvars

  terraform-destroy:
    runs-on: ubuntu-latest
    needs: terraform
    environment: destroy   # <-- environment at job level

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::111225938018:role/github-odic-chamu
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -var-file=terraform.tfvars